jobs: 
- job: windows

  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: NuGetCommand@2
    inputs:
      command: custom
      arguments: source add -Name Neo -Source TakeWing.Neo.Multiownable.Tests
    displayName: 'Added path to the packages'

  - task: NuGetCommand@2
    inputs:
      command: custom
      arguments: source list
    displayName: 'List sources'

  - task: NuGetCommand@2
    inputs:
      command: custom
      arguments: install Neo.Debugger.Core
    displayName: 'Install Neo.Debugger.Core'

  - task: NuGetCommand@2
    inputs:
      command: restore

  - script: |
      dotnet build TakeWing.Neo.Multiownable\TakeWing.Neo.Multiownable.csproj
    displayName: 'Build multiownable'