jobs: 
- job: windows

  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - script: |
      xcopy TakeWing.Neo.Multiownable.Tests\Neo.Debugger.Core.1.0.0.nupkg "C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\"
      xcopy TakeWing.Neo.Multiownable.Tests\Neo.Emulator.1.0.0.nupkg "C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\"
    displayName: 'Copy packages'

  - task: NuGetCommand@2
    inputs:
      command: custom
      arguments: install Neo.Debugger.Core
    displayName: 'Install Neo.Debugger.Core'

  - task: NuGetCommand@2
    inputs:
      command: custom
      arguments: install Neo.Emulator
    displayName: 'Install Neo.Emulator'

  - task: NuGetCommand@2
    inputs:
      command: restore

  - script: |
      dotnet build TakeWing.Neo.Multiownable\TakeWing.Neo.Multiownable.csproj
    displayName: 'Build multiownable'