jobs: 
- job: windows

  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: NuGetCommand@2
    inputs:
      command: custom
      arguments: source Add -Name CustomPackages -Source TakeWing.Neo.Multiownable.Tests
  
  - task: NuGetCommand@2
    inputs:
      command: 'restore'

  - script: |
      dotnet build TakeWing.Neo.Multiownable\TakeWing.Neo.Multiownable.csproj
    displayName: 'Build multiownable'