jobs: 
- job: windows

  pool:
    vmImage: 'vs2017-win2016'

  steps:

  - script: |
      dotnet build TakeWing.Neo.Multiownable\TakeWing.Neo.Multiownable.csproj
    displayName: 'Build Multiownable'
