jobs: 
- job: windows

  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: 'TakeWing.Neo.Multiownable\TakeWing.Neo.Multiownable.csproj'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: TakeWing.Neo.Multiownable\TakeWing.Neo.Multiownable.csproj'    

  - script: |
      dotnet build TakeWing.Neo.Multiownable\TakeWing.Neo.Multiownable.csproj
    displayName: 'Build Multiownable'
