jobs: 
- job: windows

  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - script: |
      git clone https://github.com/CityOfZion/neo-debugger-tools
      del neo-debugger-tools\NEO-Compiler\Properties\AssemblyInfo.cs
      dotnet build neo-debugger-tools\NEO-Compiler\neon.csproj
    displayName: 'Download and Build NeoCompiler'

  - script: |
      xcopy TakeWing.Neo.Multiownable.Tests\Neo.Debugger.Core.1.0.0.nupkg "C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\"
      xcopy TakeWing.Neo.Multiownable.Tests\Neo.Emulator.1.0.0.nupkg "C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\"
    displayName: 'Copy packages'

  - task: NuGetCommand@2
    inputs:
      command: custom
      arguments: install Neo.Debugger.Core -OutputDirectory packages
    displayName: 'Install Neo.Debugger.Core'

  - task: NuGetCommand@2
    inputs:
      command: custom
      arguments: install Neo.Emulator -OutputDirectory packages
    displayName: 'Install Neo.Emulator'

  - script: |
      dotnet build TakeWing.Neo.Multiownable\TakeWing.Neo.Multiownable.csproj
    displayName: 'Build Multiownable'

  - script: |
      dotnet build TakeWing.Neo.Multiownable.SmartContractsForTests\TakeWing.Neo.Multiownable.SmartContractsForTests.csproj
    displayName: 'Build Multiownable.SmartContractForTests'